// Code generated by generate-tl-files; DO NOT EDIT.

package telegram

type AccountAuthorizationForm struct {
	RequiredTypes    []SecureRequiredType
	Values           []*SecureValue
	Errors           []SecureValueError
	Users            []User
	PrivacyPolicyURL string `tl:"flag:0"`
}

func (*AccountAuthorizationForm) CRC() uint32 {
	return 0xad2e1cd8
}

func (*AccountAuthorizationForm) FlagIndex() int {
	return 0
}

type AccountAuthorizations struct {
	AuthorizationTtlDays int32
	Authorizations       []*Authorization
}

func (*AccountAuthorizations) CRC() uint32 {
	return 0x4bff8ea0
}

type AccountAutoDownloadSettings struct {
	Low    *AutoDownloadSettings
	Medium *AutoDownloadSettings
	High   *AutoDownloadSettings
}

func (*AccountAutoDownloadSettings) CRC() uint32 {
	return 0x63cacf26
}

type AccountContentSettings struct {
	SensitiveEnabled   bool `tl:"flag:0,encoded_in_bitflags"`
	SensitiveCanChange bool `tl:"flag:1,encoded_in_bitflags"`
}

func (*AccountContentSettings) CRC() uint32 {
	return 0x57e28221
}

func (*AccountContentSettings) FlagIndex() int {
	return 0
}

type AccountPassword struct {
	HasRecovery             bool            `tl:"flag:0,encoded_in_bitflags"`
	HasSecureValues         bool            `tl:"flag:1,encoded_in_bitflags"`
	HasPassword             bool            `tl:"flag:2,encoded_in_bitflags"`
	CurrentAlgo             PasswordKdfAlgo `tl:"flag:2"`
	SRPB                    []byte          `tl:"flag:2"`
	SRPID                   int64           `tl:"flag:2"`
	Hint                    string          `tl:"flag:3"`
	EmailUnconfirmedPattern string          `tl:"flag:4"`
	NewAlgo                 PasswordKdfAlgo
	NewSecureAlgo           SecurePasswordKdfAlgo
	SecureRandom            []byte
	PendingResetDate        int32 `tl:"flag:5"`
}

func (*AccountPassword) CRC() uint32 {
	return 0x185b184f
}

func (*AccountPassword) FlagIndex() int {
	return 0
}

type AccountPasswordInputSettings struct {
	NewAlgo           PasswordKdfAlgo       `tl:"flag:0"`
	NewPasswordHash   []byte                `tl:"flag:0"`
	Hint              string                `tl:"flag:0"`
	Email             string                `tl:"flag:1"`
	NewSecureSettings *SecureSecretSettings `tl:"flag:2"`
}

func (*AccountPasswordInputSettings) CRC() uint32 {
	return 0xc23727c9
}

func (*AccountPasswordInputSettings) FlagIndex() int {
	return 0
}

type AccountPasswordSettings struct {
	Email          string                `tl:"flag:0"`
	SecureSettings *SecureSecretSettings `tl:"flag:1"`
}

func (*AccountPasswordSettings) CRC() uint32 {
	return 0x9a5c33e5
}

func (*AccountPasswordSettings) FlagIndex() int {
	return 0
}

type AccountPrivacyRules struct {
	Rules []PrivacyRule
	Chats []Chat
	Users []User
}

func (*AccountPrivacyRules) CRC() uint32 {
	return 0x50a04e45
}

type AccountSentEmailCode struct {
	EmailPattern string
	Length       int32
}

func (*AccountSentEmailCode) CRC() uint32 {
	return 0x811f854f
}

type AccountTakeout struct {
	ID int64
}

func (*AccountTakeout) CRC() uint32 {
	return 0x4dba4501
}

type AccountTmpPassword struct {
	TmpPassword []byte
	ValidUntil  int32
}

func (*AccountTmpPassword) CRC() uint32 {
	return 0xdb64fd34
}

type AccountWebAuthorizations struct {
	Authorizations []*WebAuthorization
	Users          []User
}

func (*AccountWebAuthorizations) CRC() uint32 {
	return 0xed56c9fc
}

type AccountDaysTtl struct {
	Days int32
}

func (*AccountDaysTtl) CRC() uint32 {
	return 0xb8d0afdf
}

type AuthExportedAuthorization struct {
	ID    int64
	Bytes []byte
}

func (*AuthExportedAuthorization) CRC() uint32 {
	return 0xb434e2b8
}

type AuthLoggedOut struct {
	FutureAuthToken []byte `tl:"flag:0"`
}

func (*AuthLoggedOut) CRC() uint32 {
	return 0xc3a2835f
}

func (*AuthLoggedOut) FlagIndex() int {
	return 0
}

type AuthPasswordRecovery struct {
	EmailPattern string
}

func (*AuthPasswordRecovery) CRC() uint32 {
	return 0x137948a5
}

type AuthSentCode struct {
	Type          AuthSentCodeType
	PhoneCodeHash string
	NextType      AuthCodeType `tl:"flag:1"`
	Timeout       int32        `tl:"flag:2"`
}

func (*AuthSentCode) CRC() uint32 {
	return 0x5e002502
}

func (*AuthSentCode) FlagIndex() int {
	return 0
}

type Authorization struct {
	Current                   bool `tl:"flag:0,encoded_in_bitflags"`
	OfficialApp               bool `tl:"flag:1,encoded_in_bitflags"`
	PasswordPending           bool `tl:"flag:2,encoded_in_bitflags"`
	EncryptedRequestsDisabled bool `tl:"flag:3,encoded_in_bitflags"`
	CallRequestsDisabled      bool `tl:"flag:4,encoded_in_bitflags"`
	Hash                      int64
	DeviceModel               string
	Platform                  string
	SystemVersion             string
	APIID                     int32
	AppName                   string
	AppVersion                string
	DateCreated               int32
	DateActive                int32
	Ip                        string
	Country                   string
	Region                    string
}

func (*Authorization) CRC() uint32 {
	return 0xad01d61d
}

func (*Authorization) FlagIndex() int {
	return 0
}

type AutoDownloadSettings struct {
	Disabled              bool `tl:"flag:0,encoded_in_bitflags"`
	VideoPreloadLarge     bool `tl:"flag:1,encoded_in_bitflags"`
	AudioPreloadNext      bool `tl:"flag:2,encoded_in_bitflags"`
	PhonecallsLessData    bool `tl:"flag:3,encoded_in_bitflags"`
	PhotoSizeMax          int32
	VideoSizeMax          int32
	FileSizeMax           int32
	VideoUploadMaxbitrate int32
}

func (*AutoDownloadSettings) CRC() uint32 {
	return 0xe04232f3
}

func (*AutoDownloadSettings) FlagIndex() int {
	return 0
}

type AvailableReaction struct {
	Inactive          bool `tl:"flag:0,encoded_in_bitflags"`
	Reaction          string
	Title             string
	StaticIcon        Document
	AppearAnimation   Document
	SelectAnimation   Document
	ActivateAnimation Document
	EffectAnimation   Document
	AroundAnimation   Document `tl:"flag:1"`
	CenterIcon        Document `tl:"flag:1"`
}

func (*AvailableReaction) CRC() uint32 {
	return 0xc077ec01
}

func (*AvailableReaction) FlagIndex() int {
	return 0
}

type BankCardOpenURL struct {
	URL  string
	Name string
}

func (*BankCardOpenURL) CRC() uint32 {
	return 0xf568028a
}

type BotCommand struct {
	Command     string
	Description string
}

func (*BotCommand) CRC() uint32 {
	return 0xc27ac8c7
}

type BotInfo struct {
	UserID      int64
	Description string
	Commands    []*BotCommand
}

func (*BotInfo) CRC() uint32 {
	return 0x1b74b335
}

type CdnConfig struct {
	PublicKeys []*CdnPublicKey
}

func (*CdnConfig) CRC() uint32 {
	return 0x5725e40a
}

type CdnPublicKey struct {
	DcID      int32
	PublicKey string
}

func (*CdnPublicKey) CRC() uint32 {
	return 0xc982eaba
}

type ChannelAdminLogEvent struct {
	ID     int64
	Date   int32
	UserID int64
	Action ChannelAdminLogEventAction
}

func (*ChannelAdminLogEvent) CRC() uint32 {
	return 0x1fad68cd
}

type ChannelAdminLogEventsFilter struct {
	Join      bool `tl:"flag:0,encoded_in_bitflags"`
	Leave     bool `tl:"flag:1,encoded_in_bitflags"`
	Invite    bool `tl:"flag:2,encoded_in_bitflags"`
	Ban       bool `tl:"flag:3,encoded_in_bitflags"`
	Unban     bool `tl:"flag:4,encoded_in_bitflags"`
	Kick      bool `tl:"flag:5,encoded_in_bitflags"`
	Unkick    bool `tl:"flag:6,encoded_in_bitflags"`
	Promote   bool `tl:"flag:7,encoded_in_bitflags"`
	Demote    bool `tl:"flag:8,encoded_in_bitflags"`
	Info      bool `tl:"flag:9,encoded_in_bitflags"`
	Settings  bool `tl:"flag:10,encoded_in_bitflags"`
	Pinned    bool `tl:"flag:11,encoded_in_bitflags"`
	Edit      bool `tl:"flag:12,encoded_in_bitflags"`
	Delete    bool `tl:"flag:13,encoded_in_bitflags"`
	GroupCall bool `tl:"flag:14,encoded_in_bitflags"`
	Invites   bool `tl:"flag:15,encoded_in_bitflags"`
	Send      bool `tl:"flag:16,encoded_in_bitflags"`
}

func (*ChannelAdminLogEventsFilter) CRC() uint32 {
	return 0xea107ae4
}

func (*ChannelAdminLogEventsFilter) FlagIndex() int {
	return 0
}

type ChannelsAdminLogResults struct {
	Events []*ChannelAdminLogEvent
	Chats  []Chat
	Users  []User
}

func (*ChannelsAdminLogResults) CRC() uint32 {
	return 0xed8af74d
}

type ChannelsChannelParticipant struct {
	Participant ChannelParticipant
	Chats       []Chat
	Users       []User
}

func (*ChannelsChannelParticipant) CRC() uint32 {
	return 0xdfb80317
}

type ChannelsSendAsPeers struct {
	Peers []Peer
	Chats []Chat
	Users []User
}

func (*ChannelsSendAsPeers) CRC() uint32 {
	return 0x8356cda9
}

type ChatAdminRights struct {
	ChangeInfo     bool `tl:"flag:0,encoded_in_bitflags"`
	PostMessages   bool `tl:"flag:1,encoded_in_bitflags"`
	EditMessages   bool `tl:"flag:2,encoded_in_bitflags"`
	DeleteMessages bool `tl:"flag:3,encoded_in_bitflags"`
	BanUsers       bool `tl:"flag:4,encoded_in_bitflags"`
	InviteUsers    bool `tl:"flag:5,encoded_in_bitflags"`
	PinMessages    bool `tl:"flag:7,encoded_in_bitflags"`
	AddAdmins      bool `tl:"flag:9,encoded_in_bitflags"`
	Anonymous      bool `tl:"flag:10,encoded_in_bitflags"`
	ManageCall     bool `tl:"flag:11,encoded_in_bitflags"`
	Other          bool `tl:"flag:12,encoded_in_bitflags"`
}

func (*ChatAdminRights) CRC() uint32 {
	return 0x5fb224d5
}

func (*ChatAdminRights) FlagIndex() int {
	return 0
}

type ChatAdminWithInvites struct {
	AdminID             int64
	InvitesCount        int32
	RevokedInvitesCount int32
}

func (*ChatAdminWithInvites) CRC() uint32 {
	return 0xf2ecef23
}

type ChatBannedRights struct {
	ViewMessages bool `tl:"flag:0,encoded_in_bitflags"`
	SendMessages bool `tl:"flag:1,encoded_in_bitflags"`
	SendMedia    bool `tl:"flag:2,encoded_in_bitflags"`
	SendStickers bool `tl:"flag:3,encoded_in_bitflags"`
	SendGifs     bool `tl:"flag:4,encoded_in_bitflags"`
	SendGames    bool `tl:"flag:5,encoded_in_bitflags"`
	SendInline   bool `tl:"flag:6,encoded_in_bitflags"`
	EmbedLinks   bool `tl:"flag:7,encoded_in_bitflags"`
	SendPolls    bool `tl:"flag:8,encoded_in_bitflags"`
	ChangeInfo   bool `tl:"flag:10,encoded_in_bitflags"`
	InviteUsers  bool `tl:"flag:15,encoded_in_bitflags"`
	PinMessages  bool `tl:"flag:17,encoded_in_bitflags"`
	UntilDate    int32
}

func (*ChatBannedRights) CRC() uint32 {
	return 0x9f120418
}

func (*ChatBannedRights) FlagIndex() int {
	return 0
}

type ChatInviteExported struct {
	Revoked       bool `tl:"flag:0,encoded_in_bitflags"`
	Permanent     bool `tl:"flag:5,encoded_in_bitflags"`
	RequestNeeded bool `tl:"flag:6,encoded_in_bitflags"`
	Link          string
	AdminID       int64
	Date          int32
	StartDate     int32  `tl:"flag:4"`
	ExpireDate    int32  `tl:"flag:1"`
	UsageLimit    int32  `tl:"flag:2"`
	Usage         int32  `tl:"flag:3"`
	Requested     int32  `tl:"flag:7"`
	Title         string `tl:"flag:8"`
}

func (*ChatInviteExported) CRC() uint32 {
	return 0xab4a819
}

func (*ChatInviteExported) FlagIndex() int {
	return 0
}

type ChatInviteImporter struct {
	Requested  bool `tl:"flag:0,encoded_in_bitflags"`
	UserID     int64
	Date       int32
	About      string `tl:"flag:2"`
	ApprovedBy int64  `tl:"flag:1"`
}

func (*ChatInviteImporter) CRC() uint32 {
	return 0x8c5adfd9
}

func (*ChatInviteImporter) FlagIndex() int {
	return 0
}

type ChatOnlines struct {
	Onlines int32
}

func (*ChatOnlines) CRC() uint32 {
	return 0xf041e250
}

type CodeSettings struct {
	AllowFlashcall  bool     `tl:"flag:0,encoded_in_bitflags"`
	CurrentNumber   bool     `tl:"flag:1,encoded_in_bitflags"`
	AllowAppHash    bool     `tl:"flag:4,encoded_in_bitflags"`
	AllowMissedCall bool     `tl:"flag:5,encoded_in_bitflags"`
	LogoutTokens    [][]byte `tl:"flag:6"`
}

func (*CodeSettings) CRC() uint32 {
	return 0x8a6469c2
}

func (*CodeSettings) FlagIndex() int {
	return 0
}

type Config struct {
	PhonecallsEnabled       bool `tl:"flag:1,encoded_in_bitflags"`
	DefaultP2PContacts      bool `tl:"flag:3,encoded_in_bitflags"`
	PreloadFeaturedStickers bool `tl:"flag:4,encoded_in_bitflags"`
	IgnorePhoneEntities     bool `tl:"flag:5,encoded_in_bitflags"`
	RevokePmInbox           bool `tl:"flag:6,encoded_in_bitflags"`
	BlockedMode             bool `tl:"flag:8,encoded_in_bitflags"`
	PfsEnabled              bool `tl:"flag:13,encoded_in_bitflags"`
	ForceTryIpv6            bool `tl:"flag:14,encoded_in_bitflags"`
	Date                    int32
	Expires                 int32
	TestMode                bool
	ThisDc                  int32
	DcOptions               []*DcOption
	DcTxtDomainName         string
	ChatSizeMax             int32
	MegagroupSizeMax        int32
	ForwardedCountMax       int32
	OnlineUpdatePeriodMs    int32
	OfflineBlurTimeoutMs    int32
	OfflineIdleTimeoutMs    int32
	OnlineCloudTimeoutMs    int32
	NotifyCloudDelayMs      int32
	NotifyDefaultDelayMs    int32
	PushChatPeriodMs        int32
	PushChatLimit           int32
	SavedGifsLimit          int32
	EditTimeLimit           int32
	RevokeTimeLimit         int32
	RevokePmTimeLimit       int32
	RatingEDecay            int32
	StickersRecentLimit     int32
	StickersFavedLimit      int32
	ChannelsReadMediaPeriod int32
	TmpSessions             int32 `tl:"flag:0"`
	PinnedDialogsCountMax   int32
	PinnedInfolderCountMax  int32
	CallReceiveTimeoutMs    int32
	CallRingTimeoutMs       int32
	CallConnectTimeoutMs    int32
	CallPacketTimeoutMs     int32
	MeURLPrefix             string
	AutoupdateURLPrefix     string `tl:"flag:7"`
	GifSearchUsername       string `tl:"flag:9"`
	VenueSearchUsername     string `tl:"flag:10"`
	ImgSearchUsername       string `tl:"flag:11"`
	StaticMapsProvider      string `tl:"flag:12"`
	CaptionLengthMax        int32
	MessageLengthMax        int32
	WebfileDcID             int32
	SuggestedLangCode       string `tl:"flag:2"`
	LangPackVersion         int32  `tl:"flag:2"`
	BaseLangPackVersion     int32  `tl:"flag:2"`
}

func (*Config) CRC() uint32 {
	return 0x330b4067
}

func (*Config) FlagIndex() int {
	return 0
}

type Contact struct {
	UserID int64
	Mutual bool
}

func (*Contact) CRC() uint32 {
	return 0x145ade0b
}

type ContactStatus struct {
	UserID int64
	Status UserStatus
}

func (*ContactStatus) CRC() uint32 {
	return 0x16d9703b
}

type ContactsFound struct {
	MyResults []Peer
	Results   []Peer
	Chats     []Chat
	Users     []User
}

func (*ContactsFound) CRC() uint32 {
	return 0xb3134d9d
}

type ContactsImportedContacts struct {
	Imported       []*ImportedContact
	PopularInvites []*PopularContact
	RetryContacts  []int64
	Users          []User
}

func (*ContactsImportedContacts) CRC() uint32 {
	return 0x77d01c3b
}

type ContactsResolvedPeer struct {
	Peer  Peer
	Chats []Chat
	Users []User
}

func (*ContactsResolvedPeer) CRC() uint32 {
	return 0x7f077ad9
}

type DataJson struct {
	Data string
}

func (*DataJson) CRC() uint32 {
	return 0x7d748d04
}

type DcOption struct {
	Ipv6         bool `tl:"flag:0,encoded_in_bitflags"`
	MediaOnly    bool `tl:"flag:1,encoded_in_bitflags"`
	TcpoOnly     bool `tl:"flag:2,encoded_in_bitflags"`
	Cdn          bool `tl:"flag:3,encoded_in_bitflags"`
	Static       bool `tl:"flag:4,encoded_in_bitflags"`
	ThisPortOnly bool `tl:"flag:5,encoded_in_bitflags"`
	ID           int32
	IpAddress    string
	Port         int32
	Secret       []byte `tl:"flag:10"`
}

func (*DcOption) CRC() uint32 {
	return 0x18b7a10d
}

func (*DcOption) FlagIndex() int {
	return 0
}

type DialogFilter struct {
	Contacts        bool `tl:"flag:0,encoded_in_bitflags"`
	NonContacts     bool `tl:"flag:1,encoded_in_bitflags"`
	Groups          bool `tl:"flag:2,encoded_in_bitflags"`
	Broadcasts      bool `tl:"flag:3,encoded_in_bitflags"`
	Bots            bool `tl:"flag:4,encoded_in_bitflags"`
	ExcludeMuted    bool `tl:"flag:11,encoded_in_bitflags"`
	ExcludeRead     bool `tl:"flag:12,encoded_in_bitflags"`
	ExcludeArchived bool `tl:"flag:13,encoded_in_bitflags"`
	ID              int32
	Title           string
	Emoticon        string `tl:"flag:25"`
	PinnedPeers     []InputPeer
	IncludePeers    []InputPeer
	ExcludePeers    []InputPeer
}

func (*DialogFilter) CRC() uint32 {
	return 0x7438f7e8
}

func (*DialogFilter) FlagIndex() int {
	return 0
}

type DialogFilterSuggested struct {
	Filter      *DialogFilter
	Description string
}

func (*DialogFilterSuggested) CRC() uint32 {
	return 0x77744d4a
}

type EmojiKeywordsDifference struct {
	LangCode    string
	FromVersion int32
	Version     int32
	Keywords    []EmojiKeyword
}

func (*EmojiKeywordsDifference) CRC() uint32 {
	return 0x5cc761bd
}

type EmojiLanguage struct {
	LangCode string
}

func (*EmojiLanguage) CRC() uint32 {
	return 0xb3fb5361
}

type EmojiURL struct {
	URL string
}

func (*EmojiURL) CRC() uint32 {
	return 0xa575739d
}

type Error struct {
	Code int32
	Text string
}

func (*Error) CRC() uint32 {
	return 0xc4b9f9bb
}

type ExportedMessageLink struct {
	Link string
	Html string
}

func (*ExportedMessageLink) CRC() uint32 {
	return 0x5dab1af4
}

type FileHash struct {
	Offset int32
	Limit  int32
	Hash   []byte
}

func (*FileHash) CRC() uint32 {
	return 0x6242c773
}

type Folder struct {
	AutofillNewBroadcasts     bool `tl:"flag:0,encoded_in_bitflags"`
	AutofillPublicGroups      bool `tl:"flag:1,encoded_in_bitflags"`
	AutofillNewCorrespondents bool `tl:"flag:2,encoded_in_bitflags"`
	ID                        int32
	Title                     string
	Photo                     ChatPhoto `tl:"flag:3"`
}

func (*Folder) CRC() uint32 {
	return 0xff544e65
}

func (*Folder) FlagIndex() int {
	return 0
}

type FolderPeer struct {
	Peer     Peer
	FolderID int32
}

func (*FolderPeer) CRC() uint32 {
	return 0xe9baa668
}

type Game struct {
	ID          int64
	AccessHash  int64
	ShortName   string
	Title       string
	Description string
	Photo       Photo
	Document    Document `tl:"flag:0"`
}

func (*Game) CRC() uint32 {
	return 0xbdf9653b
}

func (*Game) FlagIndex() int {
	return 0
}

type GlobalPrivacySettings struct {
	ArchiveAndMuteNewNoncontactPeers bool `tl:"flag:0"`
}

func (*GlobalPrivacySettings) CRC() uint32 {
	return 0xbea2f424
}

func (*GlobalPrivacySettings) FlagIndex() int {
	return 0
}

type GroupCallParticipant struct {
	Muted           bool `tl:"flag:0,encoded_in_bitflags"`
	Left            bool `tl:"flag:1,encoded_in_bitflags"`
	CanSelfUnmute   bool `tl:"flag:2,encoded_in_bitflags"`
	JustJoined      bool `tl:"flag:4,encoded_in_bitflags"`
	Versioned       bool `tl:"flag:5,encoded_in_bitflags"`
	Min             bool `tl:"flag:8,encoded_in_bitflags"`
	MutedByYou      bool `tl:"flag:9,encoded_in_bitflags"`
	VolumeByAdmin   bool `tl:"flag:10,encoded_in_bitflags"`
	Self            bool `tl:"flag:12,encoded_in_bitflags"`
	VideoJoined     bool `tl:"flag:15,encoded_in_bitflags"`
	Peer            Peer
	Date            int32
	ActiveDate      int32 `tl:"flag:3"`
	Source          int32
	Volume          int32                      `tl:"flag:7"`
	About           string                     `tl:"flag:11"`
	RaiseHandRating int64                      `tl:"flag:13"`
	Video           *GroupCallParticipantVideo `tl:"flag:6"`
	Presentation    *GroupCallParticipantVideo `tl:"flag:14"`
}

func (*GroupCallParticipant) CRC() uint32 {
	return 0xeba636fe
}

func (*GroupCallParticipant) FlagIndex() int {
	return 0
}

type GroupCallParticipantVideo struct {
	Paused       bool `tl:"flag:0,encoded_in_bitflags"`
	Endpoint     string
	SourceGroups []*GroupCallParticipantVideoSourceGroup
	AudioSource  int32 `tl:"flag:1"`
}

func (*GroupCallParticipantVideo) CRC() uint32 {
	return 0x67753ac8
}

func (*GroupCallParticipantVideo) FlagIndex() int {
	return 0
}

type GroupCallParticipantVideoSourceGroup struct {
	Semantics string
	Sources   []int32
}

func (*GroupCallParticipantVideoSourceGroup) CRC() uint32 {
	return 0xdcb118b7
}

type GroupCallStreamChannel struct {
	Channel         int32
	Scale           int32
	LastTimestampMs int64
}

func (*GroupCallStreamChannel) CRC() uint32 {
	return 0x80eb48af
}

type HelpCountry struct {
	Hidden       bool `tl:"flag:0,encoded_in_bitflags"`
	Iso2         string
	DefaultName  string
	Name         string `tl:"flag:1"`
	CountryCodes []*HelpCountryCode
}

func (*HelpCountry) CRC() uint32 {
	return 0xc3878e23
}

func (*HelpCountry) FlagIndex() int {
	return 0
}

type HelpCountryCode struct {
	CountryCode string
	Prefixes    []string `tl:"flag:0"`
	Patterns    []string `tl:"flag:1"`
}

func (*HelpCountryCode) CRC() uint32 {
	return 0x4203c5ef
}

func (*HelpCountryCode) FlagIndex() int {
	return 0
}

type HelpInviteText struct {
	Message string
}

func (*HelpInviteText) CRC() uint32 {
	return 0x18cb9f78
}

type HelpRecentMeUrls struct {
	Urls  []RecentMeURL
	Chats []Chat
	Users []User
}

func (*HelpRecentMeUrls) CRC() uint32 {
	return 0xe0310d7
}

type HelpSupport struct {
	PhoneNumber string
	User        User
}

func (*HelpSupport) CRC() uint32 {
	return 0x17c6b5f6
}

type HelpSupportName struct {
	Name string
}

func (*HelpSupportName) CRC() uint32 {
	return 0x8c05f1c9
}

type HelpTermsOfService struct {
	Popup         bool `tl:"flag:0,encoded_in_bitflags"`
	ID            *DataJson
	Text          string
	Entities      []MessageEntity
	MinAgeConfirm int32 `tl:"flag:1"`
}

func (*HelpTermsOfService) CRC() uint32 {
	return 0x780a0310
}

func (*HelpTermsOfService) FlagIndex() int {
	return 0
}

type HighScore struct {
	Pos    int32
	UserID int64
	Score  int32
}

func (*HighScore) CRC() uint32 {
	return 0x73a379eb
}

type ImportedContact struct {
	UserID   int64
	ClientID int64
}

func (*ImportedContact) CRC() uint32 {
	return 0xc13e3c50
}

type InlineBotSwitchPm struct {
	Text       string
	StartParam string
}

func (*InlineBotSwitchPm) CRC() uint32 {
	return 0x3c20629f
}

type InputAppEvent struct {
	Time float64
	Type string
	Peer int64
	Data JsonValue
}

func (*InputAppEvent) CRC() uint32 {
	return 0x1d1b1245
}

type InputClientProxy struct {
	Address string
	Port    int32
}

func (*InputClientProxy) CRC() uint32 {
	return 0x75588b3f
}

type InputEncryptedChat struct {
	ChatID     int32
	AccessHash int64
}

func (*InputEncryptedChat) CRC() uint32 {
	return 0xf141b5e1
}

type InputFolderPeer struct {
	Peer     InputPeer
	FolderID int32
}

func (*InputFolderPeer) CRC() uint32 {
	return 0xfbd2c296
}

type InputGroupCall struct {
	ID         int64
	AccessHash int64
}

func (*InputGroupCall) CRC() uint32 {
	return 0xd8aa840f
}

type InputPeerNotifySettings struct {
	ShowPreviews bool   `tl:"flag:0"`
	Silent       bool   `tl:"flag:1"`
	MuteUntil    int32  `tl:"flag:2"`
	Sound        string `tl:"flag:3"`
}

func (*InputPeerNotifySettings) CRC() uint32 {
	return 0x9c3d198e
}

func (*InputPeerNotifySettings) FlagIndex() int {
	return 0
}

type InputPhoneCall struct {
	ID         int64
	AccessHash int64
}

func (*InputPhoneCall) CRC() uint32 {
	return 0x1e36fded
}

type InputPhoneContact struct {
	ClientID  int64
	Phone     string
	FirstName string
	LastName  string
}

func (*InputPhoneContact) CRC() uint32 {
	return 0xf392b7f4
}

type InputSecureValue struct {
	Type        SecureValueType
	Data        *SecureData       `tl:"flag:0"`
	FrontSide   InputSecureFile   `tl:"flag:1"`
	ReverseSide InputSecureFile   `tl:"flag:2"`
	Selfie      InputSecureFile   `tl:"flag:3"`
	Translation []InputSecureFile `tl:"flag:6"`
	Files       []InputSecureFile `tl:"flag:4"`
	PlainData   SecurePlainData   `tl:"flag:5"`
}

func (*InputSecureValue) CRC() uint32 {
	return 0xdb21d0a7
}

func (*InputSecureValue) FlagIndex() int {
	return 0
}

type InputSingleMedia struct {
	Media    InputMedia
	RandomID int64
	Message  string
	Entities []MessageEntity `tl:"flag:0"`
}

func (*InputSingleMedia) CRC() uint32 {
	return 0x1cc6e91f
}

func (*InputSingleMedia) FlagIndex() int {
	return 0
}

type InputStickerSetItem struct {
	Document   InputDocument
	Emoji      string
	MaskCoords *MaskCoords `tl:"flag:0"`
}

func (*InputStickerSetItem) CRC() uint32 {
	return 0xffa0a496
}

func (*InputStickerSetItem) FlagIndex() int {
	return 0
}

type InputThemeSettings struct {
	MessageColorsAnimated bool `tl:"flag:2,encoded_in_bitflags"`
	BaseTheme             BaseTheme
	AccentColor           int32
	OutboxAccentColor     int32              `tl:"flag:3"`
	MessageColors         []int32            `tl:"flag:0"`
	Wallpaper             InputWallPaper     `tl:"flag:1"`
	WallpaperSettings     *WallPaperSettings `tl:"flag:1"`
}

func (*InputThemeSettings) CRC() uint32 {
	return 0x8fde504f
}

func (*InputThemeSettings) FlagIndex() int {
	return 0
}

type InputWebDocument struct {
	URL        string
	Size       int32
	MimeType   string
	Attributes []DocumentAttribute
}

func (*InputWebDocument) CRC() uint32 {
	return 0x9bed434d
}

type Invoice struct {
	Test                     bool `tl:"flag:0,encoded_in_bitflags"`
	NameRequested            bool `tl:"flag:1,encoded_in_bitflags"`
	PhoneRequested           bool `tl:"flag:2,encoded_in_bitflags"`
	EmailRequested           bool `tl:"flag:3,encoded_in_bitflags"`
	ShippingAddressRequested bool `tl:"flag:4,encoded_in_bitflags"`
	Flexible                 bool `tl:"flag:5,encoded_in_bitflags"`
	PhoneToProvider          bool `tl:"flag:6,encoded_in_bitflags"`
	EmailToProvider          bool `tl:"flag:7,encoded_in_bitflags"`
	Currency                 string
	Prices                   []*LabeledPrice
	MaxTipAmount             int64   `tl:"flag:8"`
	SuggestedTipAmounts      []int64 `tl:"flag:8"`
}

func (*Invoice) CRC() uint32 {
	return 0xcd886e0
}

func (*Invoice) FlagIndex() int {
	return 0
}

type JsonObjectValue struct {
	Key   string
	Value JsonValue
}

func (*JsonObjectValue) CRC() uint32 {
	return 0xc0de1bd9
}

type KeyboardButtonRow struct {
	Buttons []KeyboardButton
}

func (*KeyboardButtonRow) CRC() uint32 {
	return 0x77608b83
}

type LabeledPrice struct {
	Label  string
	Amount int64
}

func (*LabeledPrice) CRC() uint32 {
	return 0xcb296bf8
}

type LangPackDifference struct {
	LangCode    string
	FromVersion int32
	Version     int32
	Strings     []LangPackString
}

func (*LangPackDifference) CRC() uint32 {
	return 0xf385c1f6
}

type LangPackLanguage struct {
	Official        bool `tl:"flag:0,encoded_in_bitflags"`
	Rtl             bool `tl:"flag:2,encoded_in_bitflags"`
	Beta            bool `tl:"flag:3,encoded_in_bitflags"`
	Name            string
	NativeName      string
	LangCode        string
	BaseLangCode    string `tl:"flag:1"`
	PluralCode      string
	StringsCount    int32
	TranslatedCount int32
	TranslationsURL string
}

func (*LangPackLanguage) CRC() uint32 {
	return 0xeeca5ce3
}

func (*LangPackLanguage) FlagIndex() int {
	return 0
}

type MaskCoords struct {
	N    int32
	X    float64
	Y    float64
	Zoom float64
}

func (*MaskCoords) CRC() uint32 {
	return 0xaed6dbb2
}

type MessageFwdHeader struct {
	Imported       bool   `tl:"flag:7,encoded_in_bitflags"`
	FromID         Peer   `tl:"flag:0"`
	FromName       string `tl:"flag:5"`
	Date           int32
	ChannelPost    int32  `tl:"flag:2"`
	PostAuthor     string `tl:"flag:3"`
	SavedFromPeer  Peer   `tl:"flag:4"`
	SavedFromMsgID int32  `tl:"flag:4"`
	PsaType        string `tl:"flag:6"`
}

func (*MessageFwdHeader) CRC() uint32 {
	return 0x5f777dce
}

func (*MessageFwdHeader) FlagIndex() int {
	return 0
}

type MessageInteractionCounters struct {
	MsgID    int32
	Views    int32
	Forwards int32
}

func (*MessageInteractionCounters) CRC() uint32 {
	return 0xad4fc9bd
}

type MessagePeerReaction struct {
	Big      bool `tl:"flag:0,encoded_in_bitflags"`
	Unread   bool `tl:"flag:1,encoded_in_bitflags"`
	PeerID   Peer
	Reaction string
}

func (*MessagePeerReaction) CRC() uint32 {
	return 0x51b67eff
}

func (*MessagePeerReaction) FlagIndex() int {
	return 0
}

type MessageRange struct {
	MinID int32
	MaxID int32
}

func (*MessageRange) CRC() uint32 {
	return 0xae30253
}

type MessageReactions struct {
	Min             bool `tl:"flag:0,encoded_in_bitflags"`
	CanSeeList      bool `tl:"flag:2,encoded_in_bitflags"`
	Results         []*ReactionCount
	RecentReactions []*MessagePeerReaction `tl:"flag:1"`
}

func (*MessageReactions) CRC() uint32 {
	return 0x4f2b9479
}

func (*MessageReactions) FlagIndex() int {
	return 0
}

type MessageReplies struct {
	Comments       bool `tl:"flag:0,encoded_in_bitflags"`
	Replies        int32
	RepliesPts     int32
	RecentRepliers []Peer `tl:"flag:1"`
	ChannelID      int64  `tl:"flag:0"`
	MaxID          int32  `tl:"flag:2"`
	ReadMaxID      int32  `tl:"flag:3"`
}

func (*MessageReplies) CRC() uint32 {
	return 0x83d60fc2
}

func (*MessageReplies) FlagIndex() int {
	return 0
}

type MessageReplyHeader struct {
	ReplyToScheduled bool `tl:"flag:2,encoded_in_bitflags"`
	ReplyToMsgID     int32
	ReplyToPeerID    Peer  `tl:"flag:0"`
	ReplyToTopID     int32 `tl:"flag:1"`
}

func (*MessageReplyHeader) CRC() uint32 {
	return 0xa6d57763
}

func (*MessageReplyHeader) FlagIndex() int {
	return 0
}

type MessageViews struct {
	Views    int32           `tl:"flag:0"`
	Forwards int32           `tl:"flag:1"`
	Replies  *MessageReplies `tl:"flag:2"`
}

func (*MessageViews) CRC() uint32 {
	return 0x455b853d
}

func (*MessageViews) FlagIndex() int {
	return 0
}

type MessagesAffectedFoundMessages struct {
	Pts      int32
	PtsCount int32
	Offset   int32
	Messages []int32
}

func (*MessagesAffectedFoundMessages) CRC() uint32 {
	return 0xef8d3e6c
}

type MessagesAffectedHistory struct {
	Pts      int32
	PtsCount int32
	Offset   int32
}

func (*MessagesAffectedHistory) CRC() uint32 {
	return 0xb45c69d1
}

type MessagesAffectedMessages struct {
	Pts      int32
	PtsCount int32
}

func (*MessagesAffectedMessages) CRC() uint32 {
	return 0x84d19185
}

type MessagesArchivedStickers struct {
	Count int32
	Sets  []StickerSetCovered
}

func (*MessagesArchivedStickers) CRC() uint32 {
	return 0x4fcba9c8
}

type MessagesBotCallbackAnswer struct {
	Alert     bool   `tl:"flag:1,encoded_in_bitflags"`
	HasURL    bool   `tl:"flag:3,encoded_in_bitflags"`
	NativeUi  bool   `tl:"flag:4,encoded_in_bitflags"`
	Message   string `tl:"flag:0"`
	URL       string `tl:"flag:2"`
	CacheTime int32
}

func (*MessagesBotCallbackAnswer) CRC() uint32 {
	return 0x36585ea4
}

func (*MessagesBotCallbackAnswer) FlagIndex() int {
	return 0
}

type MessagesBotResults struct {
	Gallery    bool `tl:"flag:0,encoded_in_bitflags"`
	QueryID    int64
	NextOffset string             `tl:"flag:1"`
	SwitchPm   *InlineBotSwitchPm `tl:"flag:2"`
	Results    []BotInlineResult
	CacheTime  int32
	Users      []User
}

func (*MessagesBotResults) CRC() uint32 {
	return 0x947ca848
}

func (*MessagesBotResults) FlagIndex() int {
	return 0
}

type MessagesChatAdminsWithInvites struct {
	Admins []*ChatAdminWithInvites
	Users  []User
}

func (*MessagesChatAdminsWithInvites) CRC() uint32 {
	return 0xb69b72d7
}

type MessagesChatFull struct {
	FullChat ChatFull
	Chats    []Chat
	Users    []User
}

func (*MessagesChatFull) CRC() uint32 {
	return 0xe5d7d19c
}

type MessagesChatInviteImporters struct {
	Count     int32
	Importers []*ChatInviteImporter
	Users     []User
}

func (*MessagesChatInviteImporters) CRC() uint32 {
	return 0x81b6b00a
}

type MessagesCheckedHistoryImportPeer struct {
	ConfirmText string
}

func (*MessagesCheckedHistoryImportPeer) CRC() uint32 {
	return 0xa24de717
}

type MessagesDiscussionMessage struct {
	Messages        []Message
	MaxID           int32 `tl:"flag:0"`
	ReadInboxMaxID  int32 `tl:"flag:1"`
	ReadOutboxMaxID int32 `tl:"flag:2"`
	UnreadCount     int32
	Chats           []Chat
	Users           []User
}

func (*MessagesDiscussionMessage) CRC() uint32 {
	return 0xa6341782
}

func (*MessagesDiscussionMessage) FlagIndex() int {
	return 0
}

type MessagesExportedChatInvites struct {
	Count   int32
	Invites []*ChatInviteExported
	Users   []User
}

func (*MessagesExportedChatInvites) CRC() uint32 {
	return 0xbdc62dcc
}

type MessagesHighScores struct {
	Scores []*HighScore
	Users  []User
}

func (*MessagesHighScores) CRC() uint32 {
	return 0x9a3bfd99
}

type MessagesHistoryImport struct {
	ID int64
}

func (*MessagesHistoryImport) CRC() uint32 {
	return 0x1662af0b
}

type MessagesHistoryImportParsed struct {
	Pm    bool   `tl:"flag:0,encoded_in_bitflags"`
	Group bool   `tl:"flag:1,encoded_in_bitflags"`
	Title string `tl:"flag:2"`
}

func (*MessagesHistoryImportParsed) CRC() uint32 {
	return 0x5e0fb7b9
}

func (*MessagesHistoryImportParsed) FlagIndex() int {
	return 0
}

type MessagesInactiveChats struct {
	Dates []int32
	Chats []Chat
	Users []User
}

func (*MessagesInactiveChats) CRC() uint32 {
	return 0xa927fec5
}

type MessagesMessageEditData struct {
	Caption bool `tl:"flag:0,encoded_in_bitflags"`
}

func (*MessagesMessageEditData) CRC() uint32 {
	return 0x26b5dde6
}

func (*MessagesMessageEditData) FlagIndex() int {
	return 0
}

type MessagesMessageReactionsList struct {
	Count      int32
	Reactions  []*MessagePeerReaction
	Chats      []Chat
	Users      []User
	NextOffset string `tl:"flag:0"`
}

func (*MessagesMessageReactionsList) CRC() uint32 {
	return 0x31bd492d
}

func (*MessagesMessageReactionsList) FlagIndex() int {
	return 0
}

type MessagesMessageViews struct {
	Views []*MessageViews
	Chats []Chat
	Users []User
}

func (*MessagesMessageViews) CRC() uint32 {
	return 0xb6c4f543
}

type MessagesPeerDialogs struct {
	Dialogs  []Dialog
	Messages []Message
	Chats    []Chat
	Users    []User
	State    *UpdatesState
}

func (*MessagesPeerDialogs) CRC() uint32 {
	return 0x3371c354
}

type MessagesPeerSettings struct {
	Settings *PeerSettings
	Chats    []Chat
	Users    []User
}

func (*MessagesPeerSettings) CRC() uint32 {
	return 0x6880b94d
}

type MessagesSearchCounter struct {
	Inexact bool `tl:"flag:1,encoded_in_bitflags"`
	Filter  MessagesFilter
	Count   int32
}

func (*MessagesSearchCounter) CRC() uint32 {
	return 0xe844ebff
}

func (*MessagesSearchCounter) FlagIndex() int {
	return 0
}

type MessagesSearchResultsCalendar struct {
	Inexact        bool `tl:"flag:0,encoded_in_bitflags"`
	Count          int32
	MinDate        int32
	MinMsgID       int32
	OffsetIDOffset int32 `tl:"flag:1"`
	Periods        []*SearchResultsCalendarPeriod
	Messages       []Message
	Chats          []Chat
	Users          []User
}

func (*MessagesSearchResultsCalendar) CRC() uint32 {
	return 0x147ee23c
}

func (*MessagesSearchResultsCalendar) FlagIndex() int {
	return 0
}

type MessagesSearchResultsPositions struct {
	Count     int32
	Positions []*SearchResultPosition
}

func (*MessagesSearchResultsPositions) CRC() uint32 {
	return 0x53b22baf
}

type MessagesSponsoredMessages struct {
	Messages []*SponsoredMessage
	Chats    []Chat
	Users    []User
}

func (*MessagesSponsoredMessages) CRC() uint32 {
	return 0x65a4c7d5
}

type MessagesVotesList struct {
	Count      int32
	Votes      []MessageUserVote
	Users      []User
	NextOffset string `tl:"flag:0"`
}

func (*MessagesVotesList) CRC() uint32 {
	return 0x823f649
}

func (*MessagesVotesList) FlagIndex() int {
	return 0
}

type NearestDc struct {
	Country   string
	ThisDc    int32
	NearestDc int32
}

func (*NearestDc) CRC() uint32 {
	return 0x8e1a1775
}

type Page struct {
	Part      bool `tl:"flag:0,encoded_in_bitflags"`
	Rtl       bool `tl:"flag:1,encoded_in_bitflags"`
	V2        bool `tl:"flag:2,encoded_in_bitflags"`
	URL       string
	Blocks    []PageBlock
	Photos    []Photo
	Documents []Document
	Views     int32 `tl:"flag:3"`
}

func (*Page) CRC() uint32 {
	return 0x98657f0d
}

func (*Page) FlagIndex() int {
	return 0
}

type PageCaption struct {
	Text   RichText
	Credit RichText
}

func (*PageCaption) CRC() uint32 {
	return 0x6f747657
}

type PageRelatedArticle struct {
	URL           string
	WebpageID     int64
	Title         string `tl:"flag:0"`
	Description   string `tl:"flag:1"`
	PhotoID       int64  `tl:"flag:2"`
	Author        string `tl:"flag:3"`
	PublishedDate int32  `tl:"flag:4"`
}

func (*PageRelatedArticle) CRC() uint32 {
	return 0xb390dc08
}

func (*PageRelatedArticle) FlagIndex() int {
	return 0
}

type PageTableCell struct {
	Header       bool     `tl:"flag:0,encoded_in_bitflags"`
	AlignCenter  bool     `tl:"flag:3,encoded_in_bitflags"`
	AlignRight   bool     `tl:"flag:4,encoded_in_bitflags"`
	ValignMiddle bool     `tl:"flag:5,encoded_in_bitflags"`
	ValignBottom bool     `tl:"flag:6,encoded_in_bitflags"`
	Text         RichText `tl:"flag:7"`
	Colspan      int32    `tl:"flag:1"`
	Rowspan      int32    `tl:"flag:2"`
}

func (*PageTableCell) CRC() uint32 {
	return 0x34566b6a
}

func (*PageTableCell) FlagIndex() int {
	return 0
}

type PageTableRow struct {
	Cells []*PageTableCell
}

func (*PageTableRow) CRC() uint32 {
	return 0xe0c0c5e5
}

type PaymentCharge struct {
	ID               string
	ProviderChargeID string
}

func (*PaymentCharge) CRC() uint32 {
	return 0xea02c27e
}

type PaymentRequestedInfo struct {
	Name            string       `tl:"flag:0"`
	Phone           string       `tl:"flag:1"`
	Email           string       `tl:"flag:2"`
	ShippingAddress *PostAddress `tl:"flag:3"`
}

func (*PaymentRequestedInfo) CRC() uint32 {
	return 0x909c3f94
}

func (*PaymentRequestedInfo) FlagIndex() int {
	return 0
}

type PaymentSavedCredentialsCard struct {
	ID    string
	Title string
}

func (*PaymentSavedCredentialsCard) CRC() uint32 {
	return 0xcdc27a1f
}

type PaymentsBankCardData struct {
	Title    string
	OpenUrls []*BankCardOpenURL
}

func (*PaymentsBankCardData) CRC() uint32 {
	return 0x3e24e573
}

type PaymentsPaymentForm struct {
	CanSaveCredentials bool `tl:"flag:2,encoded_in_bitflags"`
	PasswordMissing    bool `tl:"flag:3,encoded_in_bitflags"`
	FormID             int64
	BotID              int64
	Invoice            *Invoice
	ProviderID         int64
	URL                string
	NativeProvider     string                       `tl:"flag:4"`
	NativeParams       *DataJson                    `tl:"flag:4"`
	SavedInfo          *PaymentRequestedInfo        `tl:"flag:0"`
	SavedCredentials   *PaymentSavedCredentialsCard `tl:"flag:1"`
	Users              []User
}

func (*PaymentsPaymentForm) CRC() uint32 {
	return 0x1694761b
}

func (*PaymentsPaymentForm) FlagIndex() int {
	return 0
}

type PaymentsPaymentReceipt struct {
	Date             int32
	BotID            int64
	ProviderID       int64
	Title            string
	Description      string
	Photo            WebDocument `tl:"flag:2"`
	Invoice          *Invoice
	Info             *PaymentRequestedInfo `tl:"flag:0"`
	Shipping         *ShippingOption       `tl:"flag:1"`
	TipAmount        int64                 `tl:"flag:3"`
	Currency         string
	TotalAmount      int64
	CredentialsTitle string
	Users            []User
}

func (*PaymentsPaymentReceipt) CRC() uint32 {
	return 0x70c4fe03
}

func (*PaymentsPaymentReceipt) FlagIndex() int {
	return 0
}

type PaymentsSavedInfo struct {
	HasSavedCredentials bool                  `tl:"flag:1,encoded_in_bitflags"`
	SavedInfo           *PaymentRequestedInfo `tl:"flag:0"`
}

func (*PaymentsSavedInfo) CRC() uint32 {
	return 0xfb8fe43c
}

func (*PaymentsSavedInfo) FlagIndex() int {
	return 0
}

type PaymentsValidatedRequestedInfo struct {
	ID              string            `tl:"flag:0"`
	ShippingOptions []*ShippingOption `tl:"flag:1"`
}

func (*PaymentsValidatedRequestedInfo) CRC() uint32 {
	return 0xd1451883
}

func (*PaymentsValidatedRequestedInfo) FlagIndex() int {
	return 0
}

type PeerBlocked struct {
	PeerID Peer
	Date   int32
}

func (*PeerBlocked) CRC() uint32 {
	return 0xe8fd8014
}

type PeerNotifySettings struct {
	ShowPreviews bool   `tl:"flag:0"`
	Silent       bool   `tl:"flag:1"`
	MuteUntil    int32  `tl:"flag:2"`
	Sound        string `tl:"flag:3"`
}

func (*PeerNotifySettings) CRC() uint32 {
	return 0xaf509d20
}

func (*PeerNotifySettings) FlagIndex() int {
	return 0
}

type PeerSettings struct {
	ReportSpam            bool   `tl:"flag:0,encoded_in_bitflags"`
	AddContact            bool   `tl:"flag:1,encoded_in_bitflags"`
	BlockContact          bool   `tl:"flag:2,encoded_in_bitflags"`
	ShareContact          bool   `tl:"flag:3,encoded_in_bitflags"`
	NeedContactsException bool   `tl:"flag:4,encoded_in_bitflags"`
	ReportGeo             bool   `tl:"flag:5,encoded_in_bitflags"`
	Autoarchived          bool   `tl:"flag:7,encoded_in_bitflags"`
	InviteMembers         bool   `tl:"flag:8,encoded_in_bitflags"`
	RequestChatBroadcast  bool   `tl:"flag:10,encoded_in_bitflags"`
	GeoDistance           int32  `tl:"flag:6"`
	RequestChatTitle      string `tl:"flag:9"`
	RequestChatDate       int32  `tl:"flag:9"`
}

func (*PeerSettings) CRC() uint32 {
	return 0xa518110d
}

func (*PeerSettings) FlagIndex() int {
	return 0
}

type PhoneExportedGroupCallInvite struct {
	Link string
}

func (*PhoneExportedGroupCallInvite) CRC() uint32 {
	return 0x204bd158
}

type PhoneGroupCall struct {
	Call                   GroupCall
	Participants           []*GroupCallParticipant
	ParticipantsNextOffset string
	Chats                  []Chat
	Users                  []User
}

func (*PhoneGroupCall) CRC() uint32 {
	return 0x9e727aad
}

type PhoneGroupCallStreamChannels struct {
	Channels []*GroupCallStreamChannel
}

func (*PhoneGroupCallStreamChannels) CRC() uint32 {
	return 0xd0e482b2
}

type PhoneGroupCallStreamRtmpURL struct {
	URL string
	Key string
}

func (*PhoneGroupCallStreamRtmpURL) CRC() uint32 {
	return 0x2dbf3432
}

type PhoneGroupParticipants struct {
	Count        int32
	Participants []*GroupCallParticipant
	NextOffset   string
	Chats        []Chat
	Users        []User
	Version      int32
}

func (*PhoneGroupParticipants) CRC() uint32 {
	return 0xf47751b6
}

type PhoneJoinAsPeers struct {
	Peers []Peer
	Chats []Chat
	Users []User
}

func (*PhoneJoinAsPeers) CRC() uint32 {
	return 0xafe5623f
}

type PhonePhoneCall struct {
	PhoneCall PhoneCall
	Users     []User
}

func (*PhonePhoneCall) CRC() uint32 {
	return 0xec82e140
}

type PhoneCallProtocol struct {
	UdpP2P          bool `tl:"flag:0,encoded_in_bitflags"`
	UdpReflector    bool `tl:"flag:1,encoded_in_bitflags"`
	MinLayer        int32
	MaxLayer        int32
	LibraryVersions []string
}

func (*PhoneCallProtocol) CRC() uint32 {
	return 0xfc878fc8
}

func (*PhoneCallProtocol) FlagIndex() int {
	return 0
}

type PhotosPhoto struct {
	Photo Photo
	Users []User
}

func (*PhotosPhoto) CRC() uint32 {
	return 0x20212ca8
}

type Poll struct {
	ID             int64
	Closed         bool `tl:"flag:0,encoded_in_bitflags"`
	PublicVoters   bool `tl:"flag:1,encoded_in_bitflags"`
	MultipleChoice bool `tl:"flag:2,encoded_in_bitflags"`
	Quiz           bool `tl:"flag:3,encoded_in_bitflags"`
	Question       string
	Answers        []*PollAnswer
	ClosePeriod    int32 `tl:"flag:4"`
	CloseDate      int32 `tl:"flag:5"`
}

func (*Poll) CRC() uint32 {
	return 0x86e18161
}

func (*Poll) FlagIndex() int {
	return 1
}

type PollAnswer struct {
	Text   string
	Option []byte
}

func (*PollAnswer) CRC() uint32 {
	return 0x6ca9c2e9
}

type PollAnswerVoters struct {
	Chosen  bool `tl:"flag:0,encoded_in_bitflags"`
	Correct bool `tl:"flag:1,encoded_in_bitflags"`
	Option  []byte
	Voters  int32
}

func (*PollAnswerVoters) CRC() uint32 {
	return 0x3b6ddad2
}

func (*PollAnswerVoters) FlagIndex() int {
	return 0
}

type PollResults struct {
	Min              bool                `tl:"flag:0,encoded_in_bitflags"`
	Results          []*PollAnswerVoters `tl:"flag:1"`
	TotalVoters      int32               `tl:"flag:2"`
	RecentVoters     []int64             `tl:"flag:3"`
	Solution         string              `tl:"flag:4"`
	SolutionEntities []MessageEntity     `tl:"flag:4"`
}

func (*PollResults) CRC() uint32 {
	return 0xdcb82ea3
}

func (*PollResults) FlagIndex() int {
	return 0
}

type PopularContact struct {
	ClientID  int64
	Importers int32
}

func (*PopularContact) CRC() uint32 {
	return 0x5ce14175
}

type PostAddress struct {
	StreetLine1 string
	StreetLine2 string
	City        string
	State       string
	CountryIso2 string
	PostCode    string
}

func (*PostAddress) CRC() uint32 {
	return 0x1e8caaeb
}

type ReactionCount struct {
	Chosen   bool `tl:"flag:0,encoded_in_bitflags"`
	Reaction string
	Count    int32
}

func (*ReactionCount) CRC() uint32 {
	return 0x6fb250d1
}

func (*ReactionCount) FlagIndex() int {
	return 0
}

type ReceivedNotifyMessage struct {
	ID    int32
	Flags int32
}

func (*ReceivedNotifyMessage) CRC() uint32 {
	return 0xa384b779
}

type RestrictionReason struct {
	Platform string
	Reason   string
	Text     string
}

func (*RestrictionReason) CRC() uint32 {
	return 0xd072acb4
}

type SavedPhoneContact struct {
	Phone     string
	FirstName string
	LastName  string
	Date      int32
}

func (*SavedPhoneContact) CRC() uint32 {
	return 0x1142bd56
}

type SearchResultPosition struct {
	MsgID  int32
	Date   int32
	Offset int32
}

func (*SearchResultPosition) CRC() uint32 {
	return 0x7f648b67
}

type SearchResultsCalendarPeriod struct {
	Date     int32
	MinMsgID int32
	MaxMsgID int32
	Count    int32
}

func (*SearchResultsCalendarPeriod) CRC() uint32 {
	return 0xc9b0539f
}

type SecureCredentialsEncrypted struct {
	Data   []byte
	Hash   []byte
	Secret []byte
}

func (*SecureCredentialsEncrypted) CRC() uint32 {
	return 0x33f0ea47
}

type SecureData struct {
	Data     []byte
	DataHash []byte
	Secret   []byte
}

func (*SecureData) CRC() uint32 {
	return 0x8aeabec3
}

type SecureSecretSettings struct {
	SecureAlgo     SecurePasswordKdfAlgo
	SecureSecret   []byte
	SecureSecretID int64
}

func (*SecureSecretSettings) CRC() uint32 {
	return 0x1527bcac
}

type SecureValue struct {
	Type        SecureValueType
	Data        *SecureData     `tl:"flag:0"`
	FrontSide   SecureFile      `tl:"flag:1"`
	ReverseSide SecureFile      `tl:"flag:2"`
	Selfie      SecureFile      `tl:"flag:3"`
	Translation []SecureFile    `tl:"flag:6"`
	Files       []SecureFile    `tl:"flag:4"`
	PlainData   SecurePlainData `tl:"flag:5"`
	Hash        []byte
}

func (*SecureValue) CRC() uint32 {
	return 0x187fa0ca
}

func (*SecureValue) FlagIndex() int {
	return 0
}

type SecureValueHash struct {
	Type SecureValueType
	Hash []byte
}

func (*SecureValueHash) CRC() uint32 {
	return 0xed1ecdb0
}

type ShippingOption struct {
	ID     string
	Title  string
	Prices []*LabeledPrice
}

func (*ShippingOption) CRC() uint32 {
	return 0xb6213cdf
}

type SponsoredMessage struct {
	Recommended    bool `tl:"flag:5,encoded_in_bitflags"`
	RandomID       []byte
	FromID         Peer       `tl:"flag:3"`
	ChatInvite     ChatInvite `tl:"flag:4"`
	ChatInviteHash string     `tl:"flag:4"`
	ChannelPost    int32      `tl:"flag:2"`
	StartParam     string     `tl:"flag:0"`
	Message        string
	Entities       []MessageEntity `tl:"flag:1"`
}

func (*SponsoredMessage) CRC() uint32 {
	return 0x3a836df8
}

func (*SponsoredMessage) FlagIndex() int {
	return 0
}

type StatsBroadcastStats struct {
	Period                    *StatsDateRangeDays
	Followers                 *StatsAbsValueAndPrev
	ViewsPerPost              *StatsAbsValueAndPrev
	SharesPerPost             *StatsAbsValueAndPrev
	EnabledNotifications      *StatsPercentValue
	GrowthGraph               StatsGraph
	FollowersGraph            StatsGraph
	MuteGraph                 StatsGraph
	TopHoursGraph             StatsGraph
	InteractionsGraph         StatsGraph
	IvInteractionsGraph       StatsGraph
	ViewsBySourceGraph        StatsGraph
	NewFollowersBySourceGraph StatsGraph
	LanguagesGraph            StatsGraph
	RecentMessageInteractions []*MessageInteractionCounters
}

func (*StatsBroadcastStats) CRC() uint32 {
	return 0xbdf78394
}

type StatsMegagroupStats struct {
	Period                  *StatsDateRangeDays
	Members                 *StatsAbsValueAndPrev
	Messages                *StatsAbsValueAndPrev
	Viewers                 *StatsAbsValueAndPrev
	Posters                 *StatsAbsValueAndPrev
	GrowthGraph             StatsGraph
	MembersGraph            StatsGraph
	NewMembersBySourceGraph StatsGraph
	LanguagesGraph          StatsGraph
	MessagesGraph           StatsGraph
	ActionsGraph            StatsGraph
	TopHoursGraph           StatsGraph
	WeekdaysGraph           StatsGraph
	TopPosters              []*StatsGroupTopPoster
	TopAdmins               []*StatsGroupTopAdmin
	TopInviters             []*StatsGroupTopInviter
	Users                   []User
}

func (*StatsMegagroupStats) CRC() uint32 {
	return 0xef7ff916
}

type StatsMessageStats struct {
	ViewsGraph StatsGraph
}

func (*StatsMessageStats) CRC() uint32 {
	return 0x8999f295
}

type StatsAbsValueAndPrev struct {
	Current  float64
	Previous float64
}

func (*StatsAbsValueAndPrev) CRC() uint32 {
	return 0xcb43acde
}

type StatsDateRangeDays struct {
	MinDate int32
	MaxDate int32
}

func (*StatsDateRangeDays) CRC() uint32 {
	return 0xb637edaf
}

type StatsGroupTopAdmin struct {
	UserID  int64
	Deleted int32
	Kicked  int32
	Banned  int32
}

func (*StatsGroupTopAdmin) CRC() uint32 {
	return 0xd7584c87
}

type StatsGroupTopInviter struct {
	UserID      int64
	Invitations int32
}

func (*StatsGroupTopInviter) CRC() uint32 {
	return 0x535f779d
}

type StatsGroupTopPoster struct {
	UserID   int64
	Messages int32
	AvgChars int32
}

func (*StatsGroupTopPoster) CRC() uint32 {
	return 0x9d04af9b
}

type StatsPercentValue struct {
	Part  float64
	Total float64
}

func (*StatsPercentValue) CRC() uint32 {
	return 0xcbce2fe0
}

type StatsURL struct {
	URL string
}

func (*StatsURL) CRC() uint32 {
	return 0x47a971e0
}

type StickerPack struct {
	Emoticon  string
	Documents []int64
}

func (*StickerPack) CRC() uint32 {
	return 0x12b299d4
}

type StickerSet struct {
	Archived      bool  `tl:"flag:1,encoded_in_bitflags"`
	Official      bool  `tl:"flag:2,encoded_in_bitflags"`
	Masks         bool  `tl:"flag:3,encoded_in_bitflags"`
	Animated      bool  `tl:"flag:5,encoded_in_bitflags"`
	Videos        bool  `tl:"flag:6,encoded_in_bitflags"`
	Emojis        bool  `tl:"flag:7,encoded_in_bitflags"`
	InstalledDate int32 `tl:"flag:0"`
	ID            int64
	AccessHash    int64
	Title         string
	ShortName     string
	Thumbs        []PhotoSize `tl:"flag:4"`
	ThumbDcID     int32       `tl:"flag:4"`
	ThumbVersion  int32       `tl:"flag:4"`
	Count         int32
	Hash          int32
}

func (*StickerSet) CRC() uint32 {
	return 0xd7df217a
}

func (*StickerSet) FlagIndex() int {
	return 0
}

type StickersSuggestedShortName struct {
	ShortName string
}

func (*StickersSuggestedShortName) CRC() uint32 {
	return 0x85fea03f
}

type Theme struct {
	Creator       bool `tl:"flag:0,encoded_in_bitflags"`
	Default       bool `tl:"flag:1,encoded_in_bitflags"`
	ForChat       bool `tl:"flag:5,encoded_in_bitflags"`
	ID            int64
	AccessHash    int64
	Slug          string
	Title         string
	Document      Document         `tl:"flag:2"`
	Settings      []*ThemeSettings `tl:"flag:3"`
	Emoticon      string           `tl:"flag:6"`
	InstallsCount int32            `tl:"flag:4"`
}

func (*Theme) CRC() uint32 {
	return 0xa00e67d6
}

func (*Theme) FlagIndex() int {
	return 0
}

type ThemeSettings struct {
	MessageColorsAnimated bool `tl:"flag:2,encoded_in_bitflags"`
	BaseTheme             BaseTheme
	AccentColor           int32
	OutboxAccentColor     int32     `tl:"flag:3"`
	MessageColors         []int32   `tl:"flag:0"`
	Wallpaper             WallPaper `tl:"flag:1"`
}

func (*ThemeSettings) CRC() uint32 {
	return 0xfa58b6d4
}

func (*ThemeSettings) FlagIndex() int {
	return 0
}

type TopPeer struct {
	Peer   Peer
	Rating float64
}

func (*TopPeer) CRC() uint32 {
	return 0xedcdc05b
}

type TopPeerCategoryPeers struct {
	Category TopPeerCategory
	Count    int32
	Peers    []*TopPeer
}

func (*TopPeerCategoryPeers) CRC() uint32 {
	return 0xfb834291
}

type UpdatesState struct {
	Pts         int32
	Qts         int32
	Date        int32
	Seq         int32
	UnreadCount int32
}

func (*UpdatesState) CRC() uint32 {
	return 0xa56c2a3e
}

type UploadWebFile struct {
	Size     int32
	MimeType string
	FileType StorageFileType
	Mtime    int32
	Bytes    []byte
}

func (*UploadWebFile) CRC() uint32 {
	return 0x21e753bc
}

type UserFull struct {
	Blocked             bool `tl:"flag:0,encoded_in_bitflags"`
	PhoneCallsAvailable bool `tl:"flag:4,encoded_in_bitflags"`
	PhoneCallsPrivate   bool `tl:"flag:5,encoded_in_bitflags"`
	CanPinMessage       bool `tl:"flag:7,encoded_in_bitflags"`
	HasScheduled        bool `tl:"flag:12,encoded_in_bitflags"`
	VideoCallsAvailable bool `tl:"flag:13,encoded_in_bitflags"`
	ID                  int64
	About               string `tl:"flag:1"`
	Settings            *PeerSettings
	ProfilePhoto        Photo `tl:"flag:2"`
	NotifySettings      *PeerNotifySettings
	BotInfo             *BotInfo `tl:"flag:3"`
	PinnedMsgID         int32    `tl:"flag:6"`
	CommonChatsCount    int32
	FolderID            int32  `tl:"flag:11"`
	TtlPeriod           int32  `tl:"flag:14"`
	ThemeEmoticon       string `tl:"flag:15"`
	PrivateForwardName  string `tl:"flag:16"`
}

func (*UserFull) CRC() uint32 {
	return 0xcf366521
}

func (*UserFull) FlagIndex() int {
	return 0
}

type UsersUserFull struct {
	FullUser *UserFull
	Chats    []Chat
	Users    []User
}

func (*UsersUserFull) CRC() uint32 {
	return 0x3b6d152e
}

type VideoSize struct {
	Type         string
	W            int32
	H            int32
	Size         int32
	VideoStartTs float64 `tl:"flag:0"`
}

func (*VideoSize) CRC() uint32 {
	return 0xde33b094
}

func (*VideoSize) FlagIndex() int {
	return 0
}

type WallPaperSettings struct {
	Blur                  bool  `tl:"flag:1,encoded_in_bitflags"`
	Motion                bool  `tl:"flag:2,encoded_in_bitflags"`
	BackgroundColor       int32 `tl:"flag:0"`
	SecondBackgroundColor int32 `tl:"flag:4"`
	ThirdBackgroundColor  int32 `tl:"flag:5"`
	FourthBackgroundColor int32 `tl:"flag:6"`
	Intensity             int32 `tl:"flag:3"`
	Rotation              int32 `tl:"flag:4"`
}

func (*WallPaperSettings) CRC() uint32 {
	return 0x1dc1bca4
}

func (*WallPaperSettings) FlagIndex() int {
	return 0
}

type WebAuthorization struct {
	Hash        int64
	BotID       int64
	Domain      string
	Browser     string
	Platform    string
	DateCreated int32
	DateActive  int32
	Ip          string
	Region      string
}

func (*WebAuthorization) CRC() uint32 {
	return 0xa6f8f452
}

type WebPageAttributeTheme struct {
	Documents []Document     `tl:"flag:0"`
	Settings  *ThemeSettings `tl:"flag:1"`
}

func (*WebPageAttributeTheme) CRC() uint32 {
	return 0x54b56617
}

func (*WebPageAttributeTheme) FlagIndex() int {
	return 0
}
