name: Go TL Parser
runs-on: self-hosted

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  schedule:
        - cron: '0 */3 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Build & Run TL Parser
      run: cd ./internal/cmd/tlgen && go run . --doc

    - name: Lint
      run: gofmt -l -s -w .

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "tlgen: update TL schema files"
        commit_options: "--no-verify"
        repository: .
        commit_user_name: AmarnathCJD
        commit_user_email: 72609355+AmarnathCJD@users.noreply.github.com
        commit_author: AmarnathCJD <72609355+AmarnathCJD+@users.noreply.github.com>


